server:
  port: 8096

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: none

  h2:
    console:
      enabled: true
#      path: /h2-ui

  #All spring liquibase coonfig:  https://reflectoring.io/database-migration-spring-boot-liquibase/
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    parameters:
      textColumnType: VARCHAR(255)
    contexts: local
  sql:
    init:
      platform: h2


logging:
  level:
    sql: info
    liquibase: info

